_emacs_cmd() {
    emacs -nw $*
}
alias emacs="_emacs_cmd"


_killstr() {
    ps aux | grep $1 | awk '{ FS=" "; print $2 }' | xargs kill -s SIGTERM
}
alias killstr="_killstr"


_tree() {
    tree -L 2 $*
}
alias tree="_tree"


mycd() {
    cd "$1"
    ls
}
alias cd="mycd"