_emacs_cmd() {
    emacs -nw $*
}
alias emacs="_emacs_cmd"


_killstr() {
    ps aux | grep $1 | awk '{ FS=" "; print $2 }' | xargs kill -s SIGTERM
}
alias killstr="_killstr"


_tree() {
    tree -L 2 $*
}
alias tree="_tree"


mycd() {
    cd "$1"
    ls
}
alias cd="mycd"


_infinite_ssh() {
    remote_port=$1
    target=$2
    while true; do
        autossh -C -N -R$remote_port:localhost:22 $target
        sleep 10
    done
}
alias infinite_ssh="_infinite_ssh"