#!/bin/bash

set -e


[[ -z $SSH_USERNAME || -z $SSHPASS || -z $SSH_SERVER ]] && {
    echo "SSH_USERNAME, SSHPASS and SSH_SERVER must be set";
    exit 1;
}

log_cmd() {
    echo $*
    $*
}

ssh_cmd() {
    log_cmd sshpass -e -- ssh $SSH_USERNAME@$SSH_SERVER $*
}

move_to_server() {
    local source=$1
    local dest=$2
    [[ "$source" = */ ]] && log_cmd sshpass -e -- mkdir -p $dest
    log_cmd sshpass -e -- rsync -a $source $SSH_USERNAME@$SSH_SERVER:$dest
}


# Put my stuff here
move_to_server $HOME/important_stuff/ /home/ssh_user/backup/
